- name: Create a network
  docker_network:
    name: "{{ docker_network_name }}"

- name: Create docker container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    hostname: "{{ container_name }}"
    networks:
      - name: "{{ docker_network_name }}"
    state: started
